version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily
    allow:
      - dependency-name: '*'
        dependency-type: production
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
    schedule:
      interval: daily