name: LicenseFinder

on: [push, pull_request]

jobs:
  LicenseFinder:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install LicenseFInder
      run: gem install license_finder
    - name: LicenseFinder report
      run: license_finder report
    - name: approve all licenses
      run: |
        license_finder report -q --format=json | jq -r '.dependencies[] | .licenses[]' | sort | uniq | sed -e "s/.*/'&'/" | xargs -L1 license_finder permitted_licenses add > /dev/null
        license_finder permitted_licenses list
    - name: read restricted lisences from file
      run: <.github/workflows/restrictedLicenses.txt xargs -L1 license_finder restricted_licenses add
    - name: Run LicenseFinder compliance checking
      run: license_finder

