name: LicenseFinder

on: [push, pull_request]

jobs:
  LicenseFinder:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install LicenseFInder
      run: gem install license_finder
    - name: LicenseFinder report
      run: license_finder report
    - name: apply approved licenses
      run: |
        cat .github/workflows/approved-licenses.txt | xargs -L1 license_finder  permitted_licenses add > /dev/null
        license_finder permitted_licenses list
    - name: Run LicenseFinder compliance checking
      run: license_finder

