name: Build and publish dev-release Java distributions to sonatype.

on:
  push:
    tags:
      - \d+.\d+.\d+-dev

jobs:
  api-compatibility-check-core:
    uses: th2-net/.github/.github/workflows/japi-compliance-checker.yml@main
    with:
      projectPath: ./cradle-core
      targetJarUrl: https://s01.oss.sonatype.org/content/repositories/releases/com/exactpro/th2/cradle-core/5.0.2-dev/cradle-core-5.0.2-dev.jar
  api-compatibility-check-cassandra:
    uses: th2-net/.github/.github/workflows/japi-compliance-checker.yml@main
    with:
      projectPath: ./cradle-cassandra
      continueOnError: true
      targetJarUrl: https://s01.oss.sonatype.org/content/repositories/releases/com/exactpro/th2/cradle-cassandra/5.0.2-dev/cradle-cassandra-5.0.2-dev.jar
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Sonatype'
      runsOn: ubuntu-latest
      devRelease: true
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}