name: Build and release Java distributions to sonatype.
on:
  push:
    branches:
    - master
    - version-*
    paths:
    - gradle.properties

jobs:
  api-compatibility-check-core:
    uses: th2-net/.github/.github/workflows/japi-compliance-checker.yml@main
    with:
      projectPath: ./cradle-core
      targetJarUrl: https://s01.oss.sonatype.org/content/repositories/releases/com/exactpro/th2/cradle-core/5.0.2-dev/cradle-core-5.0.2-dev.jar
  api-compatibility-check-cassandra:
    uses: th2-net/.github/.github/workflows/japi-compliance-checker.yml@main
    with:
      projectPath: ./cradle-cassandra
      continueOnError: true
      targetJarUrl: https://s01.oss.sonatype.org/content/repositories/releases/com/exactpro/th2/cradle-cassandra/5.0.2-dev/cradle-cassandra-5.0.2-dev.jar
  build:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      scanner-enabled: false
      build-target: 'Sonatype'
      runsOn: ubuntu-latest
    secrets:
      sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
      sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      sonatypeSigningKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
      sonatypeSigningPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
  scan-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create lockfiles
        run: ./gradlew createLockFiles
      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'